travel_log = {"France": {"cities_visited": ["Paris", "Lille", "Dijon"],
                         "total_visits": 12,
                         "Feedback": "That's was a nice trip!",
                         "Rate": "Ten out of ten!",
                         },
              "Germany":{"cities_visited": ["Berlin", "Hamburg", "Stuttgart"],
                         "total_visits": 17,
                         "Feedback": "That's was quite good enough.",
                         "Rate": "7/10",
                         },
              }